development:
  rpc_host: 0.0.0.0
  rpc_port: 8001
  rpc_whitelist: "*"
  minerthreads: 2
  genesis_block: config/genesis/dev_genesis.json
  datadir: /blockchain/mcpoc_development
  chains: config/chains/development.json
  mine_when_needed: true
  max_peers: 0
  gas_limit: 500000
  gas_price: 10000000000000
  console: false
  geth_extra_opts: --ipcpath /root/.ethereum/geth_mcpoc_development.ipc
  account:
    init: true
    password: config/password
staging:
  rpc_host: 0.0.0.0
  rpc_port: 8002
  rpc_whitelist: "*"
  minerthreads: 2
  genesis_block: config/genesis/staging_genesis.json
  datadir: /blockchain/mcpoc_staging
  chains: config/chains/staging.json
  mine_when_needed: true
  max_peers: 0
  gas_limit: 500000
  gas_price: 10000000000000
  console: false
  geth_extra_opts: --ipcpath /root/.ethereum/geth_mcpoc_staging.ipc
  account:
    init: true
    password: config/password_staging
production:
  rpc_host: localhost
  rpc_port: 8101
  rpc_whitelist: "*"
  datadir: default
  network_id: 1
  max_peers: 4
  console: true
  account:
    init: false
    address:
